### ISSUE TITLE
issue about training data

### ISSUE THREAD

**Issue by suke27** [ngchc/CameraSR#1]
你好，我发些你的训练数据集里都是png 图片，这些图片是照相机或者手机拍出来的么，一般我们手机拍的都是jpg 的图输入压缩后的图，不是无损图，我知道的是GAN的方法对压缩的图无法消除振铃效应，请问你有遇到此类问题么？

**Comment by ngchc** [comment]
是的，分别使用Nikon D5500与iPhone X拍摄。我没遇到过你说的这类问题。

**Comment by suke27** [comment]
现在华为都支持到50X 数码变焦，问下你有试过几倍的超分

**Comment by ngchc** [comment]
SR倍数不是我们这个工作讨论的主要对象，在论文里对于单反/手机我们分别采用x2.9/x2.4进行实验，来讨论R-V降质与CameraSR的重要性与实际效果。对于50x的变焦，我个人认为现阶段宣传效果大于实际作用[1]。我们提出的CameraSR是一种更好的数码变焦方式，可改进多种单反/手机相机的数码变焦性能（详情请见论文）。
[1] 鹅板凳. "华为P30 Pro 50倍变焦の真相".

**Comment by suke27** [comment]
我不新建问题了哈，粗率读了下你的paper，请问你们是给了一种新的方式（R-V降质）来生成的数据集进行训练么？

**Comment by ngchc** [comment]
准确的说，是先定义了R-V降质，再以采集加后处理得到的HR/LR对来建模，与常用的生成数据集方式（Bicubic/Gaussian）有所不同。

**Comment by suke27** [comment]
en,正常我们用的是bicubic，请问下你们有试过这种方式在普通的环境下的超分结果么，比如说DIV2K数据集

**Comment by ngchc** [comment]
现有的数据集（比如DIV2K）无法实现CameraSR，因为没有提供与HR匹配的真实LR图像，这正是我们要构造新数据集City100的原因。这种方式在普通环境下的SR结果在正文实验部分及补充材料中有提供。
