### ISSUE TITLE
where can download he FOV model LR image(not interpolated image)?

### ISSUE THREAD

**Issue by ninesun127** [ngchc/CameraSR#2]
why the city100 dataset both the LR image and HR image has the same resolution?Can I get the LR images not interpolated?

**Comment by ninesun127** [comment]
and what's the specific interpolation method in LR image?

**Comment by ngchc** [comment]
Hi. For the convenience purpose, the resolution of LR images have been *bicubic* interpolated to the same resolution of HR images. A re-scaling operator can be applied to these interpolated images to generate what you want.
