### ISSUE TITLE
Issue about raw data

### ISSUE THREAD

**Issue by rainyfly** [ngchc/CameraSR#5]
Thanks for your great work.  I have downloaded your raw data, but there is no information about the raw file such as white balance ,  bayer patterns etc, and I can not recover the color images correctly, could you please release the original raw files or give us the relevant information ? Thank you very much .

**Comment by ngchc** [comment]
@rainyfly Thanks for you interest to our work. The processed color images (png format) are already made available. Please refer to the README file for the detailed information.
